### ISSUE TITLE
Add package install instructions

### ISSUE THREAD

**Issue by honglinsu** [oracle/adaptivemm#5]
Since we have pre-built rpm available for Oracle Linux 7 and 8, can we add the installation instructions? For example:

Oracle Linux 8: 
$ sudo dnf install adaptivemm

Oracle Linux 7:
$ sudo yum install adaptivemm

For x86-64 architecture, the pre-built adaptivemm package is available in the same repository as UEK Release 5 and Release 6 for Oracle Linux 7, and in the UEK Release 6 repository for Oracle Linux 8. 

For aarch64 architecture, the pre-built adaptivemm package is available in the BaseOS repository for Oracle Linux 8.

**Comment by hikerockies** [comment]
As an open source project, if this project provides package build and installation instructions for any Linux distribution, it will need to address multiple distributions. README.md already provides distribution agnostic build and install instructions. For specific distros, providing packaged version of adaptivemm is up to distro provider. So I would propose resolving this issue with following:

"For installing pre-built adaptivemm package for your Linux distribution, please refer to distro provider."

As for Oracle LInux, I can add the info you provided to a page in the wiki. Will that work?

**Comment by honglinsu** [comment]
thank you @hikerockies. Your proposal of adding a page in the wiki will work.

**Comment by hikerockies** [comment]
I have added a wiki page at https://github.com/oracle/adaptivemm/wiki/Installing-on-Oracle-Linux-systems with this information. This page is also linked to from the home wiki page.

Thanks honglinsu for your contribution and feedback.
